import { useParams, Link } from 'react-router-dom';
import { ArrowLeft, Users, BrainCircuit, Activity, Settings } from 'lucide-react';

export function StaffClassroomDetail() {
  const { id: _id } = useParams();

  // In a real app, fetch classroom details, students, and their mastery states here using `id`
  
  return (
    <div className="space-y-6 animate-fade-in-up pb-12">
      <Link to="/staff/dashboard" className="inline-flex items-center gap-2 text-slate-400 hover:text-white transition-colors mb-2 text-sm">
        <ArrowLeft className="w-4 h-4" />
        Back to Dashboard
      </Link>

      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-end gap-4">
        <div>
          <h1 className="text-3xl font-bold text-white mb-2">Algebra 101 - Fall</h1>
          <div className="flex items-center gap-4 text-sm text-slate-400">
            <span className="bg-indigo-500/20 text-indigo-300 px-2 py-1 rounded">Code: ALG-F26-9X</span>
            <span>Subject: Mathematics</span>
          </div>
        </div>
        <button className="bg-surfaceBorder hover:bg-surfaceBorder/80 text-white px-4 py-2 rounded-lg font-medium transition-colors flex items-center gap-2 text-sm border border-slate-700">
          <Settings className="w-4 h-4" />
          Settings
        </button>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8 pt-4">
        
        {/* Main Column */}
        <div className="lg:col-span-2 space-y-6">
          <section className="glass-panel p-6 rounded-2xl">
            <h2 className="text-lg font-bold text-white flex items-center gap-2 mb-6">
              <Users className="w-5 h-5 text-indigo-400" />
              Student Roster (28)
            </h2>
            
            <div className="space-y-3">
              {[1, 2, 3].map((i) => (
                <div key={i} className="bg-surfaceBorder/30 border border-surfaceBorder/50 p-4 rounded-xl flex flex-col sm:flex-row sm:items-center justify-between gap-4">
                  <div className="flex items-center gap-3">
                    <div className="w-10 h-10 rounded-full bg-indigo-500/20 flex items-center justify-center text-indigo-300 font-bold">
                      S{i}
                    </div>
                    <div>
                      <div className="font-medium text-white">Student {i}</div>
                      <div className="text-xs text-slate-400">Adaptive Path: active</div>
                    </div>
                  </div>
                  <div className="flex items-center gap-6">
                    <div className="text-right">
                      <div className="text-xs text-slate-500 uppercase tracking-wider font-bold mb-1">Avg Mastery</div>
                      <div className="text-emerald-400 font-bold">78%</div>
                    </div>
                    <button className="text-indigo-400 text-sm hover:text-indigo-300 transition-colors font-medium">View Profile</button>
                  </div>
                </div>
              ))}
            </div>
            
            <div className="mt-6 text-center text-sm text-slate-500 bg-surfaceBorder/20 p-4 rounded-lg border border-surfaceBorder/30">
              Note: Every student is progressing through their own individualized learning path generated by the adaptive engine.
            </div>
          </section>
        </div>

        {/* Sidebar */}
        <div className="space-y-6">
          <section className="glass-panel p-6 rounded-2xl">
            <h2 className="text-lg font-bold text-white flex items-center gap-2 mb-6">
              <BrainCircuit className="w-5 h-5 text-indigo-400" />
              Concept Mastery Overview
            </h2>
            <div className="space-y-4">
              <div>
                <div className="flex justify-between text-sm mb-1">
                  <span className="text-slate-300">Linear Equations</span>
                  <span className="text-emerald-400">82% avg</span>
                </div>
                <div className="w-full h-2 bg-surfaceBorder rounded-full overflow-hidden">
                  <div className="h-full bg-emerald-500" style={{ width: '82%' }}></div>
                </div>
              </div>
              <div>
                <div className="flex justify-between text-sm mb-1">
                  <span className="text-slate-300">Graphing Inequalities</span>
                  <span className="text-amber-400">45% avg</span>
                </div>
                <div className="w-full h-2 bg-surfaceBorder rounded-full overflow-hidden">
                  <div className="h-full bg-amber-500" style={{ width: '45%' }}></div>
                </div>
              </div>
            </div>
          </section>

          <section className="glass-panel p-6 rounded-2xl border-rose-500/30">
            <h2 className="text-lg font-bold text-white flex items-center gap-2 mb-6">
              <Activity className="w-5 h-5 text-rose-400" />
              Interventions Required
            </h2>
            <p className="text-sm text-slate-400 mb-4">3 students have been stuck on "Graphing Inequalities" for over 48 hours despite adaptive remediation.</p>
            <button className="w-full bg-rose-500/10 hover:bg-rose-500/20 text-rose-400 py-2 rounded-lg text-sm font-medium transition-colors border border-rose-500/30">
              Review Interventions
            </button>
          </section>
        </div>

      </div>
    </div>
  );
}
