-- Phase 5: Gemini Generated Content Persistence

-- Table: generated_content
-- Stores metadata and content generated by Gemini to avoid re-generating and track quality.
CREATE TABLE generated_content (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  student_id UUID NOT NULL REFERENCES auth.users(id),
  topic_id TEXT NOT NULL,
  concept_id TEXT NOT NULL,
  
  content_type TEXT NOT NULL, -- e.g., 'EXPLANATION', 'PRACTICE', 'HINT'
  difficulty TEXT,            -- e.g., 'EASY', 'MEDIUM', 'HARD'
  learner_level TEXT,
  
  prompt_version TEXT NOT NULL,
  model_name TEXT NOT NULL,
  model_version TEXT NOT NULL,
  
  content JSONB NOT NULL,     -- The generated text or structured JSON
  
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Index for caching checks and lookups
CREATE INDEX idx_generated_content_lookup ON generated_content(concept_id, content_type, difficulty, learner_level);
CREATE INDEX idx_generated_content_student ON generated_content(student_id);

-- RLS Policies
ALTER TABLE generated_content ENABLE ROW LEVEL SECURITY;

-- Students can read their own generated content
CREATE POLICY "Students can view own generated content"
  ON generated_content FOR SELECT
  USING (auth.uid() = student_id);

-- Students (or System on behalf of student) can insert their generated content
CREATE POLICY "Students can insert generated content"
  ON generated_content FOR INSERT
  WITH CHECK (auth.uid() = student_id);

-- Staff can view all generated content
CREATE POLICY "Staff can view all generated content"
  ON generated_content FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM profiles 
      WHERE profiles.id = auth.uid() 
      AND profiles.role IN ('teacher', 'admin')
    )
  );
